In [1]:
import numpy as np

In [3]:
arr2d = np.array([ [1,2,3],[4,5,6],[7,8,9]] )
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#accessing row
print(arr2d[0])
print(arr2d[2])

[1 2 3]
[7 8 9]


In [6]:
#accesing element of array
print(arr2d[1][2])

6


In [7]:
#using loops to change index
arr_len = arr2d.shape
print(arr_len)

(3, 3)
