In [5]:
import numpy as np
A = np.arange(5)
print(A)

[0 1 2 3 4]


In [4]:
B = np.arange(5,10)
print(B)

[5 6 7 8 9]


In [22]:
C = np.arange(1,30,2)
print(C)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [8]:
#Function of Numpy Array = sqrt()
D = np.sqrt(A)
print(D)

[0.         1.         1.41421356 1.73205081 2.        ]


In [9]:
#Function of NUmpy Array - exp() (exponantial)
E = np.exp(A)
print(E)

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [10]:
#Function of Numpy -random()
F = np.random.randn(7)
print(F)
F = np.random.randn(3,3)
print(F)

[ 0.67036437 -1.40428529  0.19430167 -2.51832224  0.90875342 -1.06334376
 -0.52128946]
[[-0.46216759 -0.69116786  0.5497677 ]
 [ 0.52891313  0.25929365 -1.24150486]
 [-0.52598419  0.80504884 -0.53847471]]


In [11]:
#Function of Numpy Array - add()
print(A)
print(B)
G = np.add(A,B)
print(G)

[0 1 2 3 4]
[5 6 7 8 9]
[ 5  7  9 11 13]


In [12]:
#Function of Numpy Array - maximum() 
A = np.array([1,5,18,10])
B = np.array([0,6,8,9])

H=np.maximum(A,B)
print(H)

[ 1  6 18 10]
