In [1]:
import numpy as np

In [3]:
x = np.array([100,400,-50,-40])
y = np.array([10,15,20,25])
cond = np.array([True,True,False,False])

z = [a if cond else b for a, cond,b in zip(x, cond,y)]
print(z)

[100, 400, 20, 25]


In [4]:
#Disadvantage
#the statements are very long

In [5]:
#Using np.where()

z2 = np.where(cond,x,y)
print(z2)

[100 400  20  25]


In [11]:
z3 = np.where(x>0, 1, 0)
print(z3)

[1 1 0 0]


In [12]:
#Standard function in NumPy
print(x.sum())

410


In [13]:
x2 = np.array([[1,2],[3,4]])
print(x2)

[[1 2]
 [3 4]]


In [15]:
print(x2.sum())
print(x2.mean())
print(x2.std())
print(x2.var())

10
2.5
1.118033988749895
1.25


In [17]:
#logical AND,OR, operation, any(), all()

cond2 = np.array([True,False,True])
#OR
print(cond2.any())
#AND
print(cond2.all())

True
False


In [20]:
#sorted function
print("Unorted")
unsorted = np.array([1,10,3,6,2,9])
print(unsorted)
print("Sorted")
unsorted.sort()
print(unsorted)

Unorted
[ 1 10  3  6  2  9]
Sorted
[ 1  2  3  6  9 10]


In [24]:
#unique
arr2 = np.array(['a','a','b','b','c'])
print(np.unique(arr2))

['a' 'b' 'c']


In [26]:
#in1d
np.in1d(['a','b','c','e'],arr2)

array([ True,  True,  True, False])