In [1]:
import numpy as np

In [3]:
#Create ID Numpy Array

mylist1 = [101,102,103]
myArray = np.array(mylist1)

print(myArray)

[101 102 103]


In [6]:
#Creating 2D NP Array

mylist2 = [201,202,203]
myArray2D = np.array([mylist1,mylist2])

print(myArray2D)

[[101 102 103]
 [201 202 203]]


In [8]:
#Findeing Dimension of Arrayshape

print("My ArrayDimension")
print(myArray.shape)
print("My Array2D Dimension")
print(myArray2D.shape)

My ArrayDimension
(3,)
My Array2D Dimension
(2, 3)


In [9]:
#Finding Datatype of arra - dtype

print("My Array Data Type")
print(myArray.dtype)
print("My Array2D Data Type")
print(myArray2D.dtype)

My Array Data Type
int32
My Array2D Data Type
int32


In [18]:
#Array creation and intaliazation function - zeroes

print("One Dimension")
zero_array = np.zeros(5)
print(zero_array)
print("Two Dimension")
zero_array2D = np.zeros([5,5])
print(zero_array2D)

One Dimension
[0. 0. 0. 0. 0.]
Two Dimension
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
#Array creation and intaliazation function - empty
#Caution the this empty function more like junction values

print("One Dimension")
empty_array = np.empty(5)
print(empty_array)
print("Two Dimension")
empty_array2D = np.empty([5,5])
print(empty_array2D)

One Dimension
[0. 0. 0. 0. 0.]
Two Dimension
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
#Array creation and intaliazation function - ones

print("One Dimension")
ones_array = np.ones(5)
print(ones_array)
print("Two Dimension")
ones_array2D = np.ones([5,5])
print(ones_array2D)

One Dimension
[1. 1. 1. 1. 1.]
Two Dimension
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
#Array creation and intaliazation function - eye
#To create identity matrics

Identity_Array = np.eye(3)
print(Identity_Array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#Array creation and intaliazation function - arrange
#To create aritmatic progression

Ap_array = np.arange(0,20,2)
print(Ap_array)

[ 0  2  4  6  8 10 12 14 16 18]
