In [9]:
import numpy as np

In [2]:
#What is scalar operation
#simple mat ops that perform of each element easy to implement and understand

In [11]:
#Scalar Array Multiplication using * operator
arr1 = np.array([[1,2,3],[5,6,7]])
print(arr1)

[[1 2 3]
 [5 6 7]]


In [12]:
arr2 = arr1 * arr1
print(arr2)

[[ 1  4  9]
 [25 36 49]]


In [13]:
#Exponantial Multiply using** array (square2)
arr3 = arr1 ** 2
print(arr3)

[[ 1  4  9]
 [25 36 49]]


In [14]:
#Scalar substraction of array elements
arr4 = arr3 - arr1
print(arr4)

[[ 0  2  6]
 [20 30 42]]


In [15]:
#Scalar Division of array elements
arr5 = 1/arr1
print(arr5)

[[1.         0.5        0.33333333]
 [0.2        0.16666667 0.14285714]]
