In [1]:
import numpy as np

In [12]:
arr = np.arange(100,120,2)
print(arr)

[100 102 104 106 108 110 112 114 116 118]


In [3]:
#Intro to indexes

In [13]:
#Access Individual array elements
print("First Elements")
print(arr[0])
print("Second Elements")
print(arr[1])

First Elements
100
Second Elements
102


In [14]:
#Slicing the array[start,stop,step]
print(arr[0:5:1])

[100 102 104 106 108]


In [15]:
#Updating array using slices
arr[0:5] = 1
arr[6:8] = 4
print(arr)

[  1   1   1   1   1 110   4   4 116 118]


In [16]:
arr[:] = 0
print(arr)

[0 0 0 0 0 0 0 0 0 0]
